version: '3.7'

services:
  dev:
    build:
      context: ./
      dockerfile: Dockerfile
      target: installer
    ports:
     - "3000:3000"
    volumes:
     - .:/app
    command: ["yarn", "start"]

